all:
  vars:
    ansible_user: "admin"
  children:
    haproxy:
      children:
        haproxy_west:
          hosts:
            vm-haproxy01:
              ansible_host: 10.10.100.10
            vm-haproxy02:
              ansible_host: 10.10.100.11
        haproxy_east:
          hosts:
            vm-easthap03:
              ansible_host: 10.10.100.218
            vm-easthap04:
              ansible_host: 10.10.100.219
    consul:
      children:
        consul_west:
          hosts:
            vm-consul01:
              ansible_host: 10.10.100.12
            vm-consul02:
              ansible_host: 10.10.100.13
            vm-consul03:
              ansible_host: 10.10.100.14
    vault:
      children:
        vault_west:
          hosts:
            vm-vault01:
              ansible_host: 10.10.100.15
            vm-vault02:
              ansible_host: 10.10.100.16
            vm-vault03:
              ansible_host: 10.10.100.17
    stolon:
      children:
        stolon_west:
          hosts:
            vm-stolon01:
              ansible_host: 10.10.100.18
            vm-stolon02:
              ansible_host: 10.10.100.19
            vm-stolon03:
              ansible_host: 10.10.100.20
    concourse:
      children:
        concourse_west:
          hosts:
            vm-concourse01:
              ansible_host: 10.10.100.21
            vm-concourse02:
              ansible_host: 10.10.100.22
            vm-concourse03:
              ansible_host: 10.10.100.23
        concourse_east:
          hosts:
            vm-eastjs01:
              ansible_host: 10.10.100.231
            vm-eastjs02:
              ansible_host: 10.10.100.232
            vm-eastque01:
              ansible_host: 10.10.100.209
            vm-eastque02:
              ansible_host: 10.10.100.210
            vm-eastque03:
              ansible_host: 10.10.100.211
    harbor:
      children:
        harbor_west:
          hosts:
            vm-harbor01:
              ansible_host: 10.10.100.24
        harbor_east:
          hosts:
            vm-easthrb02:
              ansible_host: 10.10.100.223
    etcd:
      children:
        etcd_west:
          hosts:
            vm-k8setcd01:
              ansible_host: 10.10.100.30
            vm-k8setcd02:
              ansible_host: 10.10.100.31
            vm-k8setcd03:
              ansible_host: 10.10.100.32
        etcd_east:
          hosts:
            vm-eastetc04:
              ansible_host: 10.10.100.212
            vm-eastetc05:
              ansible_host: 10.10.100.213
            vm-eastetc06:
              ansible_host: 10.10.100.214
    k8s:
      children:
        k8s_west:
          children:
            k8s_west_prod:
              children:
                k8s_west_prod_masters:
                  hosts:
                    vm-k8smstr01:
                      ansible_host: 10.10.100.33
                    vm-k8smstr02:
                      ansible_host: 10.10.100.34
                    vm-k8smstr03:
                      ansible_host: 10.10.100.35
                k8s_west_prod_workers:
                  hosts:
                    vm-k8snode01:
                      ansible_host: 10.10.100.36
                    vm-k8snode02:
                      ansible_host: 10.10.100.37
                    vm-k8snode03:
                      ansible_host: 10.10.100.38
                    vm-k8snode04:
                      ansible_host: 10.10.100.39
            k8s_west_test:
              children:
                k8s_west_test_masters:
                  hosts:
                    vm-vtk8snode01:
                      ansible_host: 10.10.100.60
                k8s_west_test_workers:
                  hosts:
                    vm-vtk8snode02:
                      ansible_host: 10.10.100.61
                    vm-vtk8snode03:
                      ansible_host: 10.10.100.62
        k8s_east:
          children:
            k8s_east_masters:
              hosts:
                vm-eastkcp01:
                  ansible_host: 10.10.100.215
                vm-eastkcp02:
                  ansible_host: 10.10.100.216
                vm-eastkcp03:
                  ansible_host: 10.10.100.217
            k8s_east_prod:
              children:
                k8s_east_prod_workers:
                  hosts:
                    vm-eastsurv01:
                      ansible_host: 10.10.100.203
                    vm-eastsurv02:
                      ansible_host: 10.10.100.204
                    vm-eastsurv03:
                      ansible_host: 10.10.100.205
                    vm-eastsurv04:
                      ansible_host: 10.10.100.206
                    vm-eastsurv05:
                      ansible_host: 10.10.100.207
                    vm-eastsurv06:
                      ansible_host: 10.10.100.208
            k8s_east_dev:
              children:
                k8s_east_dev_workers:
                  hosts:
                    vm-eastred01:
                      ansible_host: 10.10.100.233
                    vm-eastred02:
                      ansible_host: 10.10.100.234
                    vm-eastred03:
                      ansible_host: 10.10.100.235
                    vm-eastred04:
                      ansible_host: 10.10.100.236
                    vm-eastred05:
                      ansible_host: 10.10.100.237
                    vm-eastred06:
                      ansible_host: 10.10.100.238
    minio:
      children:
        minio_west:
          hosts:
            vm-minio01:
              ansible_host: 10.10.100.100
            vm-minio02:
              ansible_host: 10.10.100.101
            vm-minio03:
              ansible_host: 10.10.100.102
            vm-minio04:
              ansible_host: 10.10.100.103
            vm-minio05:
              ansible_host: 10.10.100.104
            vm-minio06:
              ansible_host: 10.10.100.105
        minio_east:
          hosts:
            vm-eastmno07:
              ansible_host: 10.10.100.224
            vm-eastmno08:
              ansible_host: 10.10.100.225
            vm-eastmno09:
              ansible_host: 10.10.100.226
            vm-eastmno10:
              ansible_host: 10.10.100.227
            vm-eastmno11:
              ansible_host: 10.10.100.228
            vm-eastmno12:
              ansible_host: 10.10.100.229
    elastic:
      children:
        elastic_west:
          hosts:
            vm-lstsrch01:
              ansible_host: 10.10.100.200
            vm-lstsrch02:
              ansible_host: 10.10.100.201
            vm-lstsrch03:
              ansible_host: 10.10.100.202
        elastic_east:
          hosts:
            vm-eastels04:
              ansible_host: 10.10.100.220
            vm-eastels05:
              ansible_host: 10.10.100.221
            vm-eastels06:
              ansible_host: 10.10.100.222
